### ISSUE TITLE
ISSUE: Cannot count mail pieces after USPS message gets archived

### ISSUE THREAD

**Issue by thisisbenwoo** [moralmunky/Home-Assistant-Mail-And-Packages#135]
Hi there,

I am running the latest versions of HA and Mail and Packages. Thank you for pointing me to the wiki, everything works now! However, after I archive my daily USPS Informed Delivery, my mail count goes back to 0. 

So, I pointed the folder instead of INBOX to All Mail. The result was not pretty:
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/mail_and_packages/sensor.py", line 161, in async_setup_entry
    sensors.append(PackagesSensor(data, variable))
  File "/config/custom_components/mail_and_packages/sensor.py", line 286, in __init__
    self.update()
  File "/config/custom_components/mail_and_packages/sensor.py", line 334, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/mail_and_packages/sensor.py", line 216, in update
    count[sensor] = get_items(account, "count")
  File "/config/custom_components/mail_and_packages/sensor.py", line 683, in get_items
    email_msg = str(msg.get_payload(0))
  File "/usr/local/lib/python3.7/email/message.py", line 257, in get_payload
    raise TypeError('Expected list, got %s' % type(self._payload))
TypeError: Expected list, got 
  File "/config/custom_components/mail_and_packages/sensor.py", line 683, in get_items
    email_msg = str(msg.get_payload(0))
  File "/usr/local/lib/python3.7/email/message.py", line 257, in get_payload
    raise TypeError('Expected list, got %s' % type(self._payload))
TypeError: Expected list, got `

Then subsequent errors look like this (about every 2 minutes or so):
`    email_msg = str(msg.get_payload(0))
  File "/usr/local/lib/python3.7/email/message.py", line 257, in get_payload
    raise TypeError('Expected list, got %s' % type(self._payload))
TypeError: Expected list, got `

`  File "/usr/local/lib/python3.7/email/message.py", line 257, in get_payload
    raise TypeError('Expected list, got %s' % type(self._payload))
TypeError: Expected list, got `

`    raise TypeError('Expected list, got %s' % type(self._payload))
TypeError: Expected list, got `

`TypeError: Expected list, got `

After this last log entry, there seems to be no more errors, but I'm also still seeing zero mail pieces (even though today, I am supposed to have 2, and when I had the USPS Informed Delivery email in my INBOX, and Mail and Packages was pointed at my INBOX, it correctly scanned and counted the 2 mail pieces).

I'm afraid I am not a programmer, so I cannot do much more than provide what I see in the logs.

TIA

b

**Comment by firstof9** [comment]
This is tripping on an Amazon email in your email.

**Comment by firstof9** [comment]
Could have sworn I fixed this.

**Comment by firstof9** [comment]
Give this a shot to replace sensor.py:

https://raw.githubusercontent.com/firstof9/Home-Assistant-Mail-And-Packages/0.2.x/custom_components/mail_and_packages/sensor.py

**Comment by thisisbenwoo** [comment]
BTW @firstof9 , I can't believe the response time on this. This is awesome. You have to put a Patreon link so I can buy you a cup of coffee at least!

**Comment by thisisbenwoo** [comment]
After a couple of restarts of HA, it looks like it parsed through "[Gmail]/All Mail". But the above error still shows in my log:

`2020-06-02 10:39:45 ERROR (MainThread) [custom_components.mail_and_packages.sensor] Error attempting prase Amazon email: Expected list, got <class 'str'>
2020-06-02 10:39:47 ERROR (MainThread) [custom_components.mail_and_packages.sensor] Error attempting prase Amazon email: Expected list, got <class 'str'>`

**Comment by firstof9** [comment]
Correct that's going to be an Amazon email in a non-multipart format, basicly the code added is skipping over that email and just outputting an error, which I should change to debug instead of error so you don't see it.

This new version will stop the messages, sorry bout that:

https://raw.githubusercontent.com/firstof9/Home-Assistant-Mail-And-Packages/0.2.x/custom_components/mail_and_packages/sensor.py

**Comment by thisisbenwoo** [comment]
No need to be sorry. I'm just amazed at the speed with which you do this. Thank you again. I've been looking for such a component.

Now, if you can just link me directly to each of the packages, that will be perfect! ;-)

**Comment by firstof9** [comment]
I'm looking into getting the tracking numbers as an attribute of the sensors. Keep an eye out for updates.
