### ISSUE TITLE
Feature: Allow reconfiguration without having to remove integration

### ISSUE THREAD

**Issue by firstof9** [moralmunky/Home-Assistant-Mail-And-Packages#53]
Add ability to allow for reconfiguration without having to remove and re-add the integration from Home Assistant.

**Comment by firstof9** [comment]
If anyone would like to test:

https://github.com/firstof9/Home-Assistant-Mail-And-Packages/tree/bug-fixes-1

@moralmunky or perhaps @FuzzyMistborn

**Comment by moralmunky** [comment]
Short answer, we don't need it.

Long answer for anyone that wants to understand why.

As someone who has resisted moving away from yaml configuration and heavily organized my configuration into drop in packages, I understand the want to keep this.

The HASS team appears to be moving away from external yaml and creating methods to store settings to without yaml. Most of the components that have become official integrations loose their yaml settings. There are also recommended way to migrate a system so you don't have to set up each individual integration by hand. This integration is not complicated and does not have extensive set up options. I also thing the ability you added to reconfigure the Integration is also a case against reinstating yaml configuration.

**Comment by firstof9** [comment]
Think this was meant for #12 hehe

**Comment by DeadEnded** [comment]
Tested the DEV branch (0.1.3-b2) and the reconfiguration is available, but does not appear to be working. I have tried changing every field, and after changing and clicking `submit` the fields go back to what they were before I modified them.

**Comment by firstof9** [comment]
0.1.3-b3 should fix this @DeadEnded

**Comment by DeadEnded** [comment]
Fantastic!  Updated to `0.1.3-b3` and confirmed reconfiguration now saves correctly!

Great Job!

**Comment by guedeaux** [comment]
This doesn't work for me on 0.1.3-b5 running Hassio 0.107.4

When trying to update the integration settings, I can't get past "Step One." When I click submit in the Step One window, I receive "Unknown error occurred" and in the logs I get:

> Logger: aiohttp.server
> Source: custom_components/mail_and_packages/config_flow.py:177
> First occurred: 11:03:43 AM (1 occurrences)
> Last logged: 11:03:43 AM
> 
> Error handling request
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
>     resp = await task
>   File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
>     resp = await handler(request)
>   File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 123, in handle
>     result = await result
>   File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 227, in post
>     return await super().post(request, flow_id)
>   File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 50, in wrapper
>     result = await method(view, request, *args, **kwargs)
>   File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 92, in post
>     result = await self._flow_mgr.async_configure(flow_id, data)
>   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 130, in async_configure
>     result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
>   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 172, in _async_handle_step
>     result: Dict = await getattr(flow, method)(user_input)
>   File "/config/custom_components/mail_and_packages/config_flow.py", line 177, in async_step_init
>     self._data.update(user_input)
> AttributeError: 'mappingproxy' object has no attribute 'update'

**Comment by firstof9** [comment]
Running a check on this now, should be fixed shortly.

**Comment by firstof9** [comment]
@guedeaux b6 should fix that for you.

**Comment by guedeaux** [comment]
Confirmed.

**Comment by moralmunky** [comment]
Receiving 'unknown error' when submitting the first screen of the integration setup.

0.1.3-b6 - Issue with the creation of the folder list

`Error handling request
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/auth.py", line 135, in auth_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/view.py", line 123, in handle
    result = await result
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/config/config_entries.py", line 163, in post
    return await super().post(request, flow_id)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/data_validator.py", line 50, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/data_entry_flow.py", line 92, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/data_entry_flow.py", line 130, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/data_entry_flow.py", line 172, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/home/homeassistant/.homeassistant/custom_components/mail_and_packages/config_flow.py", line 56, in async_step_user
    return await self.async_step_config_2()
  File "/home/homeassistant/.homeassistant/custom_components/mail_and_packages/config_flow.py", line 101, in async_step_config_2
    return await self._show_config_2(user_input)
  File "/home/homeassistant/.homeassistant/custom_components/mail_and_packages/config_flow.py", line 123, in _show_config_2
    mailboxes.append(i.decode().split(' "/" ')[1].strip('"'))
IndexError: list index out of range`

**Comment by moralmunky** [comment]
Here is what is returned for  folderlist. 

2020-03-21 14:07:04 ERROR (MainThread) [custom_components.mail_and_packages.config_flow] folders: [b'(\\HasChildren) "." INBOX', b'(\\HasNoChildren \\UnMarked \\Junk) "." INBOX.spam', b'(\\HasNoChildren \\UnMarked \\Archive) "." INBOX.Archive', b'(\\HasNoChildren \\UnMarked \\Trash) "." INBOX.Trash', b'(\\HasNoChildren \\UnMarked \\Sent) "." INBOX.Sent', b'(\\HasNoChildren \\UnMarked \\Drafts) "." INBOX.Drafts']

**Comment by firstof9** [comment]
@moralmunky Odd your's are seeming to be separated with ```"."``` rather than the standard ```"/"``` you're using Gmail right?

**Comment by moralmunky** [comment]
No, using simple email hosting in a cPanel host. Check out the fix and see if it needs any improvements. https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/commit/bec2918f7c145addcaf11d352fdc583c87693b99

I am getting the following when saving the changes on reconfig.

```
2020-03-22 00:35:40 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback async_track_state_change.<locals>.state_change_listener(<Event state_...ew_state=None>) at /srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/event.py:81
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/event.py", line 103, in state_change_listener
    event.data.get("new_state"),
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 368, in async_run_job
    target(*args)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/automation/state.py", line 92, in state_automation_listener
    call_action()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/automation/state.py", line 78, in call_action
    context=to_s.context,
AttributeError: 'NoneType' object has no attribute 'context'
2020-03-22 00:35:40 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback async_track_state_change.<locals>.state_change_listener(<Event state_...ew_state=None>) at /srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/event.py:81
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/event.py", line 103, in state_change_listener
    event.data.get("new_state"),
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 368, in async_run_job
    target(*args)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/automation/state.py", line 92, in state_automation_listener
    call_action()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/automation/state.py", line 78, in call_action
    context=to_s.context,
AttributeError: 'NoneType' object has no attribute 'context'
2020-03-22 00:35:40 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback async_track_state_change.<locals>.state_change_listener(<Event state_...ew_state=None>) at /srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/event.py:81
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/event.py", line 103, in state_change_listener
    event.data.get("new_state"),
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 368, in async_run_job
    target(*args)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/automation/state.py", line 92, in state_automation_listener
    call_action()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/automation/state.py", line 78, in call_action
    context=to_s.context,
AttributeError: 'NoneType' object has no attribute 'context'
```

**Comment by firstof9** [comment]
I'm thinking this error is from adding the scan_interval configuration, since the sensors refresh on re-config it's mucking up the Throttle function I'm thinking.

**Comment by firstof9** [comment]
Think I fixed it, just double checking it now @moralmunky, looks like it might have been something with the unloading/loading of the sensors.

**Comment by firstof9** [comment]
Actually I just figured it out, it's from the automation freaking out when the sensors unload/reload that's supposed to trigger on a state change. This is why it wasn't occurring on my dev instance.

Either way we're now properly unloading the entities so we don't get errors on integration removal.

**Comment by DeadEnded** [comment]
I changed an existing installations folder from `www` to `images` as suggested.  After a restart (changing logging working on another issue with @firstof9) I noticed in the logs that it was still trying to get the image from `www`.  I double checked with the re-configure tool and it has `images` in the path instead of `www`, but the log shows it trying to find the .gif in `www`.  Just wanted to share in this thread since a lot of work is being done here.  I changed my config back to `www` and moved the .gif there so I could keep testing.

**Comment by moralmunky** [comment]
@firstof9, running 0.1.3-b8. Reconfiguring the integration shows the change in path but the errors reported previously still show.

@DeadEnded, which version are you on? Can you better describe what you're seeing is still looking in the www folder (provide the logs)?

**Comment by DeadEnded** [comment]
@moralmunky 
looks like I am not current (sorry I didn't check this before posting).
Currently on 0.1.3-b5 (I see there is now 0.1.3-b8).
I'll update and review - thanks.

**Comment by firstof9** [comment]
> Reconfiguring the integration shows the change in path but the errors reported previously still show.

The automation(s) will need to be reworked to stop the error from coming up.
