### ISSUE TITLE
[Feature Request]   add amazon.es to amazon domains

### ISSUE THREAD

**Issue by tretabyte** [moralmunky/Home-Assistant-Mail-And-Packages#698]
**Is your feature request related to a problem? Please describe.**
Looking at amazon domains already supported I can't find amazon.es hence the request

**Describe the solution you'd like**
n/a

**Describe alternatives you've considered**
n/a

**Additional context**
I can help with examples of emails sent by amazon.es for parcel deliveries

**Comment by firstof9** [comment]
Yes please provide some example emails, thank you.

**Comment by tretabyte** [comment]
Hi Chris,

I’m attaching 2 email samples.
Amazon.es provides service in both spanish (for Spain) and Portuguese (for Portugal) so I’m attaching both if you want to add both ☺


Regards,

**Comment by firstof9** [comment]
You have to do it from github's website.

**Comment by tretabyte** [comment]
sorry my bad,
let's see if I can attach them here then
[amazon_emails.zip](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/files/9234434/amazon_emails.zip)
.

**Comment by firstof9** [comment]
Sorry these are some kind of binary format, and I can't open them.

**Comment by tretabyte** [comment]
you can't open what's inside the zip?
I zipped 2 emails saved from outlook, let's try like this
![image](https://user-images.githubusercontent.com/60727013/182195827-46609809-5b48-4bb1-b9a5-04d739637035.png)
![image](https://user-images.githubusercontent.com/60727013/182196244-9f81356a-7aae-4c1e-a8b6-6a2dd414916e.png)

**Comment by firstof9** [comment]
I might be able to do something with this.
What does the subject line look like when a package has been delivered?

**Comment by tretabyte** [comment]
We never get an email confirming it got delivered, at least not from amazon

**Comment by firstof9** [comment]
Yikes ok

**Comment by firstof9** [comment]
Please test out `0.3.5-b6` it should pickup your amazon emails now.

**Comment by tretabyte** [comment]
Hi @firstof9 
been testing version 0.3.5-b6 but with no luck, just to make sure everything was up to date I deleted and force downloaded the beta version, redid  all configurations but nothing seems to be picked up.
right now I have 3 emails that should be picked up but nothing shows as per screenshot
![image](https://user-images.githubusercontent.com/60727013/182364301-926ad75b-c362-4584-8d4b-93d4bae3d0e1.png)

**Comment by firstof9** [comment]
Please [enable debugging](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/Troubleshooting#enable-debugging) so we can see what's going on.

**Comment by tretabyte** [comment]
I think I found the issue, I'm attaching the debug log but looks like your are tracking order-update@amazon.es, shipment-tracking@amazon.es and conferma-spedizione@amazon.es but amazon.es sends everything under only 2 email addresses (auto-confirm@amazon.es) when you do the order and (confirmar-envio@amazon.es) when the order gets sent.
[mail_debug.log](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/files/9243857/mail_debug.log)

**Comment by tretabyte** [comment]
btw I'm getting extra errors on things I didn't turn on, for example usps camera
[mail2_debug.log](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/files/9243975/mail2_debug.log)
.

**Comment by firstof9** [comment]
`0.3.5-b7` should catch the email now.

**Comment by tretabyte** [comment]
Hi @firstof9 
thanks for the quick turnback but looks like there's something wrong with the dates that gets captured, I've attached the debug logs.
`2022-08-03 11:01:53 DEBUG (SyncWorker_2) [custom_components.mail_and_packages.helpers] Arrive Date: Sexta-feira, Agosto 5

Acompanhar
2022-08-03 11:01:53 DEBUG (SyncWorker_2) [custom_components.mail_and_packages.helpers] International dates not supported. (time data 'Sexta-feira, Agosto 5\n\nAcompanhar' does not match format '%A, %B %d')`

[mail_new_debug.log](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/files/9250403/mail_new_debug.log)

**Comment by firstof9** [comment]
This should be sorted in the latest beta. Let me know.

**Comment by tretabyte** [comment]
Hi,

still getting the same data error from above although it's already running with 0.3.5.-b8

**Comment by firstof9** [comment]
Seems like it's in Portuguese, I'll add that as a lang.

**Comment by firstof9** [comment]
`0.3.5-b9` should have this working now.

**Comment by tretabyte** [comment]
you must be starting to hate me lol but seems that something is still not picking the date right
```
2022-08-04 01:46:14.190 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Arrive Date: Sexta-feira, Agosto 5

Acompanhar
2022-08-04 01:46:14.213 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] International dates not supported. (time data 'Sexta-feira, Agosto 5\n\nAcompanhar' does not match format '%A, %B %d')
```

**Comment by firstof9** [comment]
Odd that it's grabbing after the date as well. Oh duh, I know why. Jeez I'm blind lol
I'll get another beta for you shortly.

**Comment by tretabyte** [comment]
you really are going to start calling me names or to pt_PT but..
```
2022-08-04 13:57:30.336 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Amazon emails found: 0
2022-08-04 13:57:30.336 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Amazon email search address: ['shipment-tracking@amazon.es', 'conferma-spedizione@amazon.es', 'confirmar-envio@amazon.es']
2022-08-04 13:57:30.337 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] DEBUG subject: None
2022-08-04 13:57:30.337 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] DEBUG imap_search: (OR OR FROM "shipment-tracking@amazon.es" FROM "conferma-spedizione@amazon.es" FROM "confirmar-envio@amazon.es" SINCE 28-Jul-2022)
2022-08-04 13:57:30.688 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] DEBUG email_search value: ('OK', [b'1000 1001 1002'])
2022-08-04 13:57:30.689 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Amazon emails found: 3
2022-08-04 13:57:31.564 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Email Multipart: True
2022-08-04 13:57:31.573 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Content Type: multipart/alternative
2022-08-04 13:57:31.573 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Amazon Subject: O seu pedido Amazon.es de "Mando a Distancia de..." foi enviado!
2022-08-04 13:57:31.574 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Looking for: will arrive:
2022-08-04 13:57:31.585 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Looking for: estimated delivery date is:
2022-08-04 13:57:31.586 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Looking for: guaranteed delivery date is:
2022-08-04 13:57:31.586 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Looking for: Arriving:
2022-08-04 13:57:31.586 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Looking for: Arriverà:
2022-08-04 13:57:31.586 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Looking for: arriving:
2022-08-04 13:57:31.586 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Looking for: Dostawa:
2022-08-04 13:57:31.586 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Looking for: Zustellung:
2022-08-04 13:57:31.586 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Looking for: Entrega:
2022-08-04 13:57:31.586 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Looking for: A chegar:
2022-08-04 13:57:31.586 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] First pass: Sexta-feira, Agosto 5
2022-08-04 13:57:31.586 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Arrive Date: Sexta-feira, Agosto 5
2022-08-04 13:57:31.587 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] International dates not supported. (time data 'Sexta-feira, Agosto 5' does not match format '%A, %B %d')
2022-08-04 13:57:31.588 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Arrive Date: Sexta-feira, Agosto 5
2022-08-04 13:57:31.607 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] International dates not supported. (time data 'Sexta-feira, Agosto 5' does not match format '%A, %B %d')
2022-08-04 13:57:31.607 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Arrive Date: Sexta-feira, Agosto 5
2022-08-04 13:57:31.622 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] International dates not supported. (time data 'Sexta-feira, Agosto 5' does not match format '%A, %B %d')
2022-08-04 13:57:31.622 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Arrive Date: Sexta-feira, Agosto 5
2022-08-04 13:57:31.623 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] International dates not supported. (time data 'Sexta-feira, Agosto 5' does not match format '%A, %B %d')
2022-08-04 13:57:31.623 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Arrive Date: Sexta-feira, Agosto 5
2022-08-04 13:57:31.628 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] International dates not supported. (time data 'Sexta-feira, Agosto 5' does not match format '%A, %B %d')
2022-08-04 13:57:31.628 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Arrive Date: Sexta-feira, Agosto 5
2022-08-04 13:57:31.629 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] International dates not supported. (time data 'Sexta-feira, Agosto 5' does not match format '%A, %B %d')
2022-08-04 13:57:31.629 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Arrive Date: Sexta-feira, Agosto 5
2022-08-04 13:57:31.630 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] International dates not supported. (time data 'Sexta-feira, Agosto 5' does not match format '%A, %B %d')
2022-08-04 13:57:31.630 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Arrive Date: Sexta-feira, Agosto 5
2022-08-04 13:57:31.630 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] International dates not supported. (time data 'Sexta-feira, Agosto 5' does not match format '%A, %B %d')
2022-08-04 13:57:31.630 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Arrive Date: Sexta-feira, Agosto 5
2022-08-04 13:57:31.645 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] International dates not supported. (time data 'Sexta-feira, Agosto 5' does not match format '%A, %B %d')
2022-08-04 13:57:31.646 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Arrive Date: Sexta-feira, Agosto 5
2022-08-04 13:57:31.647 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] International dates not supported. (time data 'Sexta-feira, Agosto 5' does not match format '%A, %B %d')
2022-08-04 13:57:31.647 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Arrive Date: Sexta-feira, Agosto 5
2022-08-04 13:57:31.664 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] International dates not supported. (time data 'Sexta-feira, Agosto 5' does not match format '%A, %B %d')
2022-08-04 13:57:31.664 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Arrive Date: Sexta-feira, Agosto 5
2022-08-04 13:57:31.665 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] International dates not supported. (time data 'Sexta-feira, Agosto 5' does not match format '%A, %B %d')
2022-08-04 13:57:31.665 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Arrive Date: Sexta-feira, Agosto 5
2022-08-04 13:57:31.666 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] International dates not supported. (time data 'Sexta-feira, Agosto 5' does not match format '%A, %B %d')
2022-08-04 13:57:32.381 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Email Multipart: True
```
![image](https://user-images.githubusercontent.com/60727013/182853764-fd1ceeea-85ff-43e4-9b81-fa10ced49211.png)

I also don't know why it keeps pulling the USPS camera since I never picked that option

**Comment by firstof9** [comment]
This looks correct, I guess I should add a debug message to when the date's taken correctly.
You won't see any count until the 5th.

The cameras are always there, for now.

**Comment by tretabyte** [comment]
but shouldn't it pick up the package which has the delivery date on the Aug 5th?

**Comment by tretabyte** [comment]
Hi,

I'm attaching the full debug log because I think there's several things that might not be working as expected.
today's the 5th so at least 1 package should be listed for delivery but I'm not getting any  results shown, there's also still the lang error showing specially on the new email I got with delivery date on the 11th, snippet below (you can see everything in the full log)
```
2022-08-05 12:52:10.304 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Arrive Date: Quinta-feira, Agosto 11


O
2022-08-05 12:52:10.322 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Invalid date format found for language pt_PT. (time data 'Quinta-feira, Agosto 11\n\n\nO' does not match format '%A, %B %d')
2022-08-05 12:52:10.322 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Arrive Date: Quinta-feira, Agosto 11


O
2022-08-05 12:52:10.323 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Invalid date format found for language pt_PT.UTF-8. (time data 'Quinta-feira, Agosto 11\n\n\nO' does not match format '%A, %B %d')
2022-08-05 12:52:10.323 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Arrive Date: Quinta-feira, Agosto 11


O
2022-08-05 12:52:10.324 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Invalid date format found for language pt_BR. (time data 'Quinta-feira, Agosto 11\n\n\nO' does not match format '%A, %B %d')
2022-08-05 12:52:10.324 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Arrive Date: Quinta-feira, Agosto 11


O
2022-08-05 12:52:10.336 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Invalid date format found for language pt_BR.UTF-8. (time data 'Quinta-feira, Agosto 11\n\n\nO' does not match format '%A, %B %d')
2022-08-05 12:52:10.337 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Arrive Date: Quinta-feira, Agosto 11


O
2022-08-05 12:52:10.340 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Invalid date format found for language . (time data 'Quinta-feira, Agosto 11\n\n\nO' does not match format '%A, %B %d')
```
[mail_debug.log](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/files/9268374/mail_debug.log)

I'm also noticing a lot of unavailable errors with this latest b12 version
![image](https://user-images.githubusercontent.com/60727013/183074095-21db9d32-c99a-4b7b-b512-3a087d0bc54b.png)

**Comment by firstof9** [comment]
Unavailable should only show up if the emails can't be parsed. The log you've attached doesn't show this occurring.

As for the date, it might be due to the day not having a zero in front of the `5`. I'm going to try a few things.

**Comment by firstof9** [comment]
Based on the documentation it should be working, so I'm not sure why it's not parsing the date.

**Comment by tretabyte** [comment]
To not let this close by inactivity, the issue still occurs with being more and more unavailable

**Comment by firstof9** [comment]
Have you tried the latest beta and updating HA to the latest version?

**Comment by tretabyte** [comment]
Hi @firstof9 ,

sorry for the late reply, took a few days off and just came back today, been updating everything to the latest version and seems something still doesn't work, I can't get anything to get populated
from logs can still see 
```
2022-08-30 01:18:59.594 DEBUG (SyncWorker_7) [custom_components.mail_and_packages.helpers] Invalid date format found for language pt_PT. (time data 'Quarta-feira, Agosto 31' does not match format '%A, %B %d')
2022-08-30 01:18:59.594 DEBUG (SyncWorker_7) [custom_components.mail_and_packages.helpers] Arrive Date: Quarta-feira, Agosto 31
```
I know I have packages that was going to be delivered today (well yesterday now) and some today and tomorrow but never gets shown which is weird unless this error from the log is really blocking it from being picked up.
[full_debug.log](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/files/9448677/full_debug.log)

**Comment by firstof9** [comment]
I'm unsure why it's doing that, maybe the language is missing from your container or OS?

**Comment by tretabyte** [comment]
is there a way to make sure the lang is in place?
don't really know  where to look for because the entire thing was built using the iso image for NAS

**Comment by firstof9** [comment]
You can try executing: `apk add musl-locales` in the container but I'm not sure if it'll work.

**Comment by tretabyte** [comment]
```
➜  ~ apk add musl-locales
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
(1/1) Installing musl-locales (0.1.0-r0)
Executing busybox-1.35.0-r15.trigger
OK: 284 MiB in 188 packages
```
let's see how it goes now

**Comment by tretabyte** [comment]
seems it didn't do the trick, just noticed the log and I still see the error, right now I have 3 orders to be delivered today and 2 tomorrow and nothing gets picked up and the weird on all this is, in exception of the error for the date, nothing else seems to fail.
```
2022-09-01 13:56:56.056 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Email Multipart: True
2022-09-01 13:56:56.056 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Content Type: multipart/alternative
2022-09-01 13:56:56.056 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Amazon Subject: O seu pedido Amazon.es de "meross Humidificador..." e mais 1
 produtos foi enviado!
2022-09-01 13:56:56.057 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Looking for: will arrive:
2022-09-01 13:56:56.057 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Looking for: estimated delivery date is:
2022-09-01 13:56:56.057 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Looking for: guaranteed delivery date is:
2022-09-01 13:56:56.057 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Looking for: Arriving:
2022-09-01 13:56:56.057 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Looking for: Arriverà:
2022-09-01 13:56:56.057 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Looking for: arriving:
2022-09-01 13:56:56.058 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Looking for: Dostawa:
2022-09-01 13:56:56.058 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Looking for: Zustellung:
2022-09-01 13:56:56.058 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Looking for: Entrega:
2022-09-01 13:56:56.058 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Looking for: A chegar:
2022-09-01 13:56:56.058 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] First pass: Sexta-feira, Setembro 2
2022-09-01 13:56:56.058 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Arrive Date: Sexta-feira, Setembro 2
2022-09-01 13:56:56.059 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Invalid date format found for language it_IT. (time data 'Sexta-feira, Setembro 2' does not match format '%A, %B %d')
2022-09-01 13:56:56.059 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Arrive Date: Sexta-feira, Setembro 2
2022-09-01 13:56:56.077 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Invalid date format found for language it_IT.UTF-8. (time data 'Sexta-feira, Setembro 2' does not match format '%A, %B %d')
2022-09-01 13:56:56.077 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Arrive Date: Sexta-feira, Setembro 2
2022-09-01 13:56:56.079 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Invalid date format found for language pl_PL. (time data 'Sexta-feira, Setembro 2' does not match format '%A, %B %d')
2022-09-01 13:56:56.079 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Arrive Date: Sexta-feira, Setembro 2
2022-09-01 13:56:56.080 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Invalid date format found for language pl_PL.UTF-8. (time data 'Sexta-feira, Setembro 2' does not match format '%A, %B %d')
2022-09-01 13:56:56.080 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Arrive Date: Sexta-feira, Setembro 2
2022-09-01 13:56:56.081 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Invalid date format found for language de_DE. (time data 'Sexta-feira, Setembro 2' does not match format '%A, %B %d')
2022-09-01 13:56:56.081 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Arrive Date: Sexta-feira, Setembro 2
2022-09-01 13:56:56.082 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Invalid date format found for language de_DE.UTF-8. (time data 'Sexta-feira, Setembro 2' does not match format '%A, %B %d')
2022-09-01 13:56:56.082 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Arrive Date: Sexta-feira, Setembro 2
2022-09-01 13:56:56.099 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Invalid date format found for language es_ES. (time data 'Sexta-feira, Setembro 2' does not match format '%A, %B %d')
2022-09-01 13:56:56.099 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Arrive Date: Sexta-feira, Setembro 2
2022-09-01 13:56:56.102 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Invalid date format found for language es_ES.UTF-8. (time data 'Sexta-feira, Setembro 2' does not match format '%A, %B %d')
2022-09-01 13:56:56.102 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Arrive Date: Sexta-feira, Setembro 2
2022-09-01 13:56:56.113 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Invalid date format found for language pt_PT. (time data 'Sexta-feira, Setembro 2' does not match format '%A, %B %d')
2022-09-01 13:56:56.113 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Arrive Date: Sexta-feira, Setembro 2
2022-09-01 13:56:56.116 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Invalid date format found for language pt_PT.UTF-8. (time data 'Sexta-feira, Setembro 2' does not match format '%A, %B %d')
2022-09-01 13:56:56.116 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Arrive Date: Sexta-feira, Setembro 2
2022-09-01 13:56:56.117 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Invalid date format found for language pt_BR. (time data 'Sexta-feira, Setembro 2' does not match format '%A, %B %d')
2022-09-01 13:56:56.117 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Arrive Date: Sexta-feira, Setembro 2
2022-09-01 13:56:56.158 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Invalid date format found for language pt_BR.UTF-8. (time data 'Sexta-feira, Setembro 2' does not match format '%A, %B %d')
2022-09-01 13:56:56.160 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Arrive Date: Sexta-feira, Setembro 2
2022-09-01 13:56:56.161 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Invalid date format found for language . (time data 'Sexta-feira, Setembro 2' does not match format '%A, %B %d')
2022-09-01 13:56:56.161 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Amazon order: ['408-2026852-2734720', '408-5046837-5143519', '408-8778423-1537939']
2022-09-01 13:56:56.161 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Sensor: amazon_packages Count: 0
2022-09-01 13:56:56.162 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Sensor: zpackages_delivered Count: 0
2022-09-01 13:56:56.162 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Sensor: zpackages_transit Count: 0
```
