### ISSUE TITLE
ISSUE: Detected blocking call to open inside the event loop (HA 2024.6 beta)

### ISSUE THREAD

**Issue by SeanPM5** [moralmunky/Home-Assistant-Mail-And-Packages#897]
**Describe the bug**
Updated to Home Assistant 2024.6 beta and there's warnings in logs related to Mail and Packages custom integration. Says to report to integration author, so here goes.

**Environment (please complete the following information):**
Home Assistant OS / core version 2024.6.0b3 / Mail and Packages version 0.3.25

**Logs**
```
Logger: homeassistant.util.loop
Source: util/loop.py:81
First occurred: May 30, 2024 at 11:29:09 PM (64 occurrences)
Last logged: 1:54:25 AM

Detected blocking call to open inside the event loop by custom integration 'mail_and_packages' at custom_components/mail_and_packages/helpers.py, line 314: with open(filename, "rb") as file: (offender: /config/custom_components/mail_and_packages/helpers.py, line 314: with open(filename, "rb") as file:), please create a bug report at https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/issues
```

**Comment by firstof9** [comment]
Should be fixed in `0.3.26`

**Comment by SeanPM5** [comment]
Tested `0.3.26` and while it fixed the issue reported in OP, now there seems to be another:

* Detected blocking call to open inside the event loop by custom integration 'mail_and_packages' at custom_components/mail_and_packages/helpers.py, line 306: copyfile(mail_none, os.path.join(path, image_name)) (offender: /usr/local/lib/python3.12/shutil.py, line 260: with open(src, 'rb') as fsrc:), please create a bug report at https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/issues

**Comment by firstof9** [comment]
Ok I've added more fixes to `0.3.27b0` please give that a try. Thanks!

**Comment by SeanPM5** [comment]
Seems to be one final issue remaining in `0.3.27b0` which doesn't happen at startup like those others, only occurs after the first refresh (I have a 10 min scan interval).

* Detected blocking call to open inside the event loop by custom integration 'mail_and_packages' at custom_components/mail_and_packages/camera.py, line 116: with open(self._file_path, "rb") as file: (offender: /config/custom_components/mail_and_packages/camera.py, line 116: with open(self._file_path, "rb") as file:), please create a bug report at https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/issues

**Comment by firstof9** [comment]
Ok that's been sorted in `0.3.27b1`, let me know if you see anything else, as always thanks!

**Comment by SeanPM5** [comment]
No issues in `0.3.27b1` so far,  seems good now. Will re-open if I spot anything else.

Thanks for the fast fixes!

**Comment by clowncracker** [comment]
@firstof9 sorry to open an old ticket, but I feel like it's relevant.  I'm getting the following warning in my logs:

```Logger: homeassistant.util.loop
Source: util/loop.py:84
First occurred: 12:49:32 PM (48 occurrences)
Last logged: 5:08:18 PM

Detected blocking call to open inside the event loop by custom integration 'mail_and_packages' at custom_components/mail_and_packages/helpers.py, line 1148: with open(filepath, "wb") as the_file: (offender: /config/custom_components/mail_and_packages/helpers.py, line 1148: with open(filepath, "wb") as the_file:), please create a bug report at https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/issues Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/config/custom_components/mail_and_packages/helpers.py", line 1148, in download_img with open(filepath, "wb") as the_file:```

**Comment by firstof9** [comment]
Please open a new issue.
